database:
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.show_sql: true
    hibernate.generate_statistics: false
    hibernate.hbm2ddl.auto: create
    hibernate.c3p0.min_size: 5
    hibernate.c3p0.max_size: 20
    hibernate.c3p0.acquire_increment: 5
    hibernate.c3p0.timeout: 1800
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:./target/revolut


server:
  applicationConnectors:
    - type: http
      port: 8080

  adminConnectors:
    - type: http
      port: 8081


logging:
  level: INFO
  loggers:
    me.shihab.revolut: INFO
    org.hibernate.SQL:
      level: DEBUG

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB
